"""Manifest generation.

Everything this app applies to the cluster is produced here, as plain Kubernetes
objects, and rendered with yaml.safe_dump. The UI can show you the exact YAML
before anything is applied -- there is no hidden state.
"""
from __future__ import annotations

import base64
import secrets
from typing import Any

import yaml

from .catalog import community_version
from .models import CommunitySpec, EnterpriseSpec, OperatorInstallSpec


class _Dumper(yaml.SafeDumper):
    """Readable output: no anchors/aliases, block scalars for multi-line strings."""

    def ignore_aliases(self, data):      # repeated label maps must not become &id001
        return True


def _str_representer(dumper, data):
    if "\n" in data:                     # redis.conf etc. -> literal block style
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_representer)


def dump(objs: list[dict[str, Any]]) -> str:
    return yaml.dump_all(objs, Dumper=_Dumper, sort_keys=False,
                         default_flow_style=False, width=120)


def gen_password(n: int = 24) -> str:
    alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    return "".join(secrets.choice(alphabet) for _ in range(n))


# ============================================================ community

def redis_conf(spec: CommunitySpec) -> str:
    v = community_version(spec.version_id) or {}
    feats = set(v.get("features", []))

    lines = [
        "# generated by redis-deployer",
        "# --- network ---",
        "bind 0.0.0.0",
        "port 6379",
        "protected-mode no",
        "tcp-keepalive 300",
        "timeout 0",
        "",
        "# --- persistence ---",
        "dir /data",
    ]

    if spec.persistence in ("aof", "both"):
        lines += ["appendonly yes", f"appendfsync {spec.appendfsync}"]
    else:
        lines += ["appendonly no"]

    if spec.persistence in ("rdb", "both"):
        lines += ["save 900 1", "save 300 10", "save 60 10000"]
    else:
        lines += ['save ""']

    lines += [
        "",
        "# --- memory ---",
        f"maxmemory {spec.maxmemory}",
        f"maxmemory-policy {spec.maxmemory_policy}",
    ]
    if spec.maxmemory_clients and "maxmemory_clients" in feats:
        lines.append(f"maxmemory-clients {spec.maxmemory_clients}")
    if spec.io_threads and "io_threads" in feats:
        lines.append(f"io-threads {spec.io_threads}")

    lines += [
        "",
        "# --- logging: stdout, so `oc logs` works ---",
        "loglevel notice",
        'logfile ""',
        "",
    ]
    return "\n".join(lines)


def community_manifests(spec: CommunitySpec, password: str) -> list[dict]:
    if spec.topology == "replication":
        return community_replication_manifests(spec, password)
    return _community_standalone(spec, password)


def _community_standalone(spec: CommunitySpec, password: str) -> list[dict]:
    v = community_version(spec.version_id) or {}
    image = spec.custom_image or v.get("image") or "docker.io/redis:7.4-alpine"
    name = spec.name
    ns = spec.namespace
    labels = {"app": name, "app.kubernetes.io/name": name,
              "app.kubernetes.io/managed-by": "redis-deployer"}
    persistent = spec.persistence != "none"

    objs: list[dict] = [
        {"apiVersion": "v1", "kind": "Namespace",
         "metadata": {"name": ns, "labels": {"name": ns}}},
        {"apiVersion": "v1", "kind": "ConfigMap",
         "metadata": {"name": f"{name}-config", "namespace": ns, "labels": labels},
         "data": {"redis.conf": redis_conf(spec)}},
    ]

    if spec.auth_enabled:
        objs.append({
            "apiVersion": "v1", "kind": "Secret",
            "metadata": {"name": f"{name}-auth", "namespace": ns, "labels": labels},
            "type": "Opaque",
            "data": {"redis-password": base64.b64encode(password.encode()).decode()},
        })

    if persistent:
        pvc: dict[str, Any] = {
            "apiVersion": "v1", "kind": "PersistentVolumeClaim",
            "metadata": {"name": f"{name}-data", "namespace": ns, "labels": labels},
            "spec": {"accessModes": ["ReadWriteOnce"],
                     "resources": {"requests": {"storage": spec.storage_size}}},
        }
        if spec.storage_class:
            pvc["spec"]["storageClassName"] = spec.storage_class
        objs.append(pvc)

    # ---- container ----
    command = ["redis-server", "/etc/redis/redis.conf"]
    env = []
    if spec.auth_enabled:
        command += ["--requirepass", "$(REDIS_PASSWORD)"]
        env.append({"name": "REDIS_PASSWORD", "valueFrom": {
            "secretKeyRef": {"name": f"{name}-auth", "key": "redis-password"}}})

    if spec.auth_enabled:
        ready_cmd = ['redis-cli -a "$REDIS_PASSWORD" --no-auth-warning ping | grep -q PONG']
    else:
        ready_cmd = ["redis-cli ping | grep -q PONG"]

    mounts = [{"name": "config", "mountPath": "/etc/redis", "readOnly": True}]
    volumes: list[dict] = [{"name": "config", "configMap": {"name": f"{name}-config"}}]
    if persistent:
        mounts.insert(0, {"name": "data", "mountPath": "/data"})
        volumes.insert(0, {"name": "data",
                           "persistentVolumeClaim": {"claimName": f"{name}-data"}})
    else:
        mounts.insert(0, {"name": "data", "mountPath": "/data"})
        volumes.insert(0, {"name": "data", "emptyDir": {}})

    deployment = {
        "apiVersion": "apps/v1", "kind": "Deployment",
        "metadata": {"name": name, "namespace": ns, "labels": labels},
        "spec": {
            "replicas": 1,
            # Recreate: an RWO PVC cannot attach to two pods at once.
            "strategy": {"type": "Recreate"},
            "selector": {"matchLabels": {"app": name}},
            "template": {
                "metadata": {"labels": labels},
                "spec": {
                    "securityContext": {
                        "runAsNonRoot": True,
                        "seccompProfile": {"type": "RuntimeDefault"},
                    },
                    "containers": [{
                        "name": "redis",
                        "image": image,
                        "imagePullPolicy": "IfNotPresent",
                        "command": command,
                        "env": env,
                        "ports": [{"name": "redis", "containerPort": 6379, "protocol": "TCP"}],
                        "securityContext": {
                            "allowPrivilegeEscalation": False,
                            "capabilities": {"drop": ["ALL"]},
                        },
                        "resources": {
                            "requests": {"cpu": spec.cpu_request, "memory": spec.memory_request},
                            "limits": {"cpu": spec.cpu_limit, "memory": spec.memory_limit},
                        },
                        "volumeMounts": mounts,
                        "startupProbe": {
                            "tcpSocket": {"port": 6379},
                            "periodSeconds": 5, "failureThreshold": 30,
                        },
                        "readinessProbe": {
                            "exec": {"command": ["sh", "-c", *ready_cmd]},
                            "periodSeconds": 10, "timeoutSeconds": 3,
                        },
                        "livenessProbe": {
                            "tcpSocket": {"port": 6379},
                            "periodSeconds": 15, "timeoutSeconds": 5, "failureThreshold": 3,
                        },
                    }],
                    "volumes": volumes,
                },
            },
        },
    }
    if not env:
        deployment["spec"]["template"]["spec"]["containers"][0].pop("env")
    objs.append(deployment)

    svc: dict[str, Any] = {
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": name, "namespace": ns, "labels": labels},
        "spec": {
            "type": spec.service_type,
            "selector": {"app": name},
            "ports": [{"name": "redis", "port": 6379, "targetPort": 6379, "protocol": "TCP"}],
        },
    }
    if spec.service_type == "NodePort" and spec.node_port:
        svc["spec"]["ports"][0]["nodePort"] = spec.node_port
    objs.append(svc)

    if spec.allow_namespaces:
        objs.append(network_policy(ns, {"app": name}, 6379, spec.allow_namespaces,
                                   f"allow-clients-to-{name}"))
    return objs


# ============================================================ enterprise

def network_policy(ns: str, pod_labels: dict, port: int,
                   allow_ns: list[str], name: str, *,
                   peer_ports: list[int] | None = None,
                   allow_peers: bool = True) -> dict:
    """Allow ingress on `port` from the listed namespaces, plus peer traffic.

    Two things this has to get right, both of which fail silently:

    1. Namespaces are selected on `kubernetes.io/metadata.name`, which
       Kubernetes sets automatically on every namespace (since 1.21). A
       hand-rolled `name:` label usually does not exist, and a selector
       matching nothing does NOT mean "allow all" -- the rule simply has no
       sources, so all ingress is denied.

    2. Any multi-pod topology needs the pods to reach EACH OTHER. A policy
       that only lists client namespaces blocks replica -> primary
       replication, Sentinel's monitoring and the Redis Cluster bus, because
       the Redis pods are not in a client namespace. `allow_peers` adds a
       bare podSelector rule, which means "pods in THIS namespace matching".
    """
    ingress: list[dict] = []

    if allow_ns:
        ingress.append({
            "from": [{"namespaceSelector": {
                "matchLabels": {"kubernetes.io/metadata.name": n}}}
                for n in allow_ns],
            "ports": [{"protocol": "TCP", "port": port}],
        })

    if allow_peers:
        ports = [{"protocol": "TCP", "port": p} for p in
                 sorted({port, *(peer_ports or [])})]
        ingress.append({
            "from": [{"podSelector": {"matchLabels": pod_labels}}],
            "ports": ports,
        })

    return {
        "apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy",
        "metadata": {"name": name, "namespace": ns},
        "spec": {
            "podSelector": {"matchLabels": pod_labels},
            "policyTypes": ["Ingress"],
            "ingress": ingress,
        },
    }


def enterprise_namespace(spec: EnterpriseSpec) -> list[dict]:
    return [{
        "apiVersion": "v1", "kind": "Namespace",
        "metadata": {
            "name": spec.namespace,
            "labels": {
                "name": spec.namespace,
                "pod-security.kubernetes.io/enforce": "baseline",
                "pod-security.kubernetes.io/audit": "restricted",
                "pod-security.kubernetes.io/warn": "restricted",
            },
        },
    }]


def enterprise_license(spec: EnterpriseSpec) -> list[dict]:
    if not spec.license_text:
        return []
    return [{
        "apiVersion": "v1", "kind": "Secret",
        "metadata": {"name": "rec-license", "namespace": spec.namespace},
        "type": "Opaque",
        "data": {"license": base64.b64encode(spec.license_text.encode()).decode()},
    }]


def enterprise_operator(spec: EnterpriseSpec) -> list[dict]:
    sub: dict[str, Any] = {
        "apiVersion": "operators.coreos.com/v1alpha1", "kind": "Subscription",
        "metadata": {"name": spec.package, "namespace": spec.namespace},
        "spec": {
            "channel": spec.channel,
            "name": spec.package,
            "source": spec.catalog_source,
            "sourceNamespace": "openshift-marketplace",
            "installPlanApproval": spec.approval,
        },
    }
    if spec.starting_csv:
        sub["spec"]["startingCSV"] = spec.starting_csv
    return [
        {"apiVersion": "operators.coreos.com/v1", "kind": "OperatorGroup",
         "metadata": {"name": f"{spec.namespace}-og", "namespace": spec.namespace},
         "spec": {"targetNamespaces": [spec.namespace]}},
        sub,
    ]


def enterprise_rec(spec: EnterpriseSpec) -> list[dict]:
    rec: dict[str, Any] = {
        "apiVersion": "app.redislabs.com/v1", "kind": "RedisEnterpriseCluster",
        "metadata": {"name": spec.rec_name, "namespace": spec.namespace},
        "spec": {
            "nodes": spec.nodes,
            "redisEnterpriseNodeResources": {
                # requests == limits -> Guaranteed QoS -> evicted last
                "requests": {"cpu": spec.cpu, "memory": spec.memory},
                "limits": {"cpu": spec.cpu, "memory": spec.memory},
            },
            "bootstrapperResources": {
                "requests": {"cpu": "100m", "memory": "256Mi"},
                "limits": {"cpu": "200m", "memory": "512Mi"},
            },
            "redisEnterpriseServicesRiggerResources": {
                "requests": {"cpu": "100m", "memory": "256Mi"},
                "limits": {"cpu": "500m", "memory": "512Mi"},
            },
            "persistentSpec": {"enabled": True, "volumeSize": spec.volume_size},
            "uiServiceType": "ClusterIP",
        },
    }
    if spec.storage_class:
        rec["spec"]["persistentSpec"]["storageClassName"] = spec.storage_class
    if spec.license_text:
        rec["spec"]["licenseSecretName"] = "rec-license"
    if spec.rack_aware_label:
        rec["spec"]["rackAwarenessNodeLabel"] = spec.rack_aware_label
    if spec.priority_class:
        rec["spec"]["priorityClassName"] = spec.priority_class
    return [rec]


def enterprise_redb(spec: EnterpriseSpec) -> list[dict]:
    db: dict[str, Any] = {
        "apiVersion": "app.redislabs.com/v1alpha1", "kind": "RedisEnterpriseDatabase",
        "metadata": {"name": spec.db_name, "namespace": spec.namespace},
        "spec": {
            "redisEnterpriseCluster": {"name": spec.rec_name},
            "memorySize": spec.db_memory,
            "shardCount": spec.shard_count,
            "replication": spec.replication,
            "databasePort": spec.db_port,
            "evictionPolicy": spec.db_eviction,
            "persistence": spec.db_persistence,
        },
    }
    if spec.tls_mode:
        db["spec"]["tlsMode"] = spec.tls_mode
    return [db]


# ============================================================ generic operator

def operator_install(spec: OperatorInstallSpec) -> list[dict]:
    """OperatorGroup + Subscription for any OperatorHub package.

    AllNamespaces installs into openshift-operators, which already has a
    cluster-wide OperatorGroup -- adding a second one there breaks every
    operator in that namespace, so we do not create one.
    """
    objs: list[dict] = []
    ns = spec.namespace

    if spec.install_mode != "AllNamespaces":
        objs.append({"apiVersion": "v1", "kind": "Namespace",
                     "metadata": {"name": ns, "labels": {"name": ns}}})
        targets = ([ns] if spec.install_mode == "OwnNamespace"
                   else [spec.target_namespace or ns])
        objs.append({
            "apiVersion": "operators.coreos.com/v1", "kind": "OperatorGroup",
            "metadata": {"name": f"{spec.package}-og", "namespace": ns},
            "spec": {"targetNamespaces": targets},
        })

    sub: dict[str, Any] = {
        "apiVersion": "operators.coreos.com/v1alpha1", "kind": "Subscription",
        "metadata": {"name": spec.package, "namespace": ns},
        "spec": {
            "channel": spec.channel,
            "name": spec.package,
            "source": spec.catalog_source,
            "sourceNamespace": "openshift-marketplace",
            "installPlanApproval": spec.approval,
        },
    }
    if spec.starting_csv:
        sub["spec"]["startingCSV"] = spec.starting_csv
    objs.append(sub)
    return objs


def enterprise_ui_route(spec: EnterpriseSpec) -> list[dict]:
    """Passthrough Route to the Redis Enterprise console.

    This works where a Route for Redis itself cannot: the console speaks HTTPS,
    so the browser sends TLS SNI and HAProxy can route on it without decrypting.
    `balance: source` is required -- the console keeps server-side session state
    across the REC pods, and without sticky sessions a login lands on one pod and
    the next request on another, which presents as a login that silently fails.
    """
    return [{
        "apiVersion": "route.openshift.io/v1", "kind": "Route",
        "metadata": {
            "name": f"{spec.rec_name}-ui",
            "namespace": spec.namespace,
            "annotations": {"haproxy.router.openshift.io/balance": "source"},
        },
        "spec": {
            "to": {"kind": "Service", "name": f"{spec.rec_name}-ui"},
            "port": {"targetPort": 8443},
            "tls": {"termination": "passthrough",
                    "insecureEdgeTerminationPolicy": "None"},
        },
    }]


def community_replication_manifests(spec: CommunitySpec, password: str) -> list[dict]:
    """Primary + replicas as a StatefulSet.

    `<name>-0` is the primary; every other ordinal starts with `replicaof <name>-0`.
    A StatefulSet is required because each pod needs a stable name (the replicas
    address the primary by DNS) and its own PVC.

    NO AUTOMATIC FAILOVER. If <name>-0 dies, Kubernetes restarts it and the
    replicas reconnect -- but nothing promotes a replica in the meantime. This is
    read scaling and a warm standby. For real HA use Sentinel via the operator.
    """
    v = community_version(spec.version_id) or {}
    image = spec.custom_image or v.get("image") or "docker.io/redis:7.4-alpine"
    name, ns = spec.name, spec.namespace
    headless = f"{name}-headless"
    labels = {"app": name, "app.kubernetes.io/name": name,
              "app.kubernetes.io/managed-by": "redis-deployer",
              "redis-deployer/topology": "replication"}

    # entrypoint: ordinal 0 is the primary, everyone else replicates from it
    boot = (
        'ORD="${HOSTNAME##*-}"\n'
        'CONF=/tmp/redis.conf\n'
        'cp /etc/redis/redis.conf "$CONF"\n'
        'if [ "$ORD" != "0" ]; then\n'
        f'  echo "replicaof {name}-0.{headless}.{ns}.svc 6379" >> "$CONF"\n'
        '  echo "replica-read-only yes" >> "$CONF"\n'
        'fi\n'
        'if [ -n "$REDIS_PASSWORD" ]; then\n'
        '  echo "requirepass $REDIS_PASSWORD" >> "$CONF"\n'
        '  echo "masterauth $REDIS_PASSWORD" >> "$CONF"\n'
        'fi\n'
        'exec redis-server "$CONF"\n'
    )

    env = []
    if spec.auth_enabled:
        env.append({"name": "REDIS_PASSWORD", "valueFrom": {
            "secretKeyRef": {"name": f"{name}-auth", "key": "redis-password"}}})
        ready = 'redis-cli -a "$REDIS_PASSWORD" --no-auth-warning ping | grep -q PONG'
    else:
        ready = "redis-cli ping | grep -q PONG"

    objs: list[dict] = [
        {"apiVersion": "v1", "kind": "Namespace",
         "metadata": {"name": ns, "labels": {"name": ns}}},
        {"apiVersion": "v1", "kind": "ConfigMap",
         "metadata": {"name": f"{name}-config", "namespace": ns, "labels": labels},
         "data": {"redis.conf": redis_conf(spec)}},
    ]
    if spec.auth_enabled:
        objs.append({
            "apiVersion": "v1", "kind": "Secret",
            "metadata": {"name": f"{name}-auth", "namespace": ns, "labels": labels},
            "type": "Opaque",
            "data": {"redis-password": base64.b64encode(password.encode()).decode()},
        })

    # headless service: gives every pod a stable DNS name for peer discovery
    objs.append({
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": headless, "namespace": ns, "labels": labels},
        "spec": {"clusterIP": "None", "selector": {"app": name},
                 "publishNotReadyAddresses": True,
                 "ports": [{"name": "redis", "port": 6379, "targetPort": 6379}]},
    })

    sts: dict[str, Any] = {
        "apiVersion": "apps/v1", "kind": "StatefulSet",
        "metadata": {"name": name, "namespace": ns, "labels": labels},
        "spec": {
            "serviceName": headless,
            "replicas": max(2, spec.replicas),
            "podManagementPolicy": "OrderedReady",   # the primary must exist first
            "selector": {"matchLabels": {"app": name}},
            "template": {
                "metadata": {"labels": labels},
                "spec": {
                    "securityContext": {"runAsNonRoot": True,
                                        "seccompProfile": {"type": "RuntimeDefault"}},
                    "affinity": {"podAntiAffinity": {
                        "preferredDuringSchedulingIgnoredDuringExecution": [{
                            "weight": 100,
                            "podAffinityTerm": {
                                "topologyKey": "kubernetes.io/hostname",
                                "labelSelector": {"matchLabels": {"app": name}}},
                        }]}},
                    "containers": [{
                        "name": "redis",
                        "image": image,
                        "imagePullPolicy": "IfNotPresent",
                        "command": ["sh", "-c", boot],
                        "env": env,
                        "ports": [{"name": "redis", "containerPort": 6379}],
                        "securityContext": {"allowPrivilegeEscalation": False,
                                            "capabilities": {"drop": ["ALL"]}},
                        "resources": {
                            "requests": {"cpu": spec.cpu_request,
                                         "memory": spec.memory_request},
                            "limits": {"cpu": spec.cpu_limit,
                                       "memory": spec.memory_limit}},
                        "volumeMounts": [
                            {"name": "data", "mountPath": "/data"},
                            {"name": "config", "mountPath": "/etc/redis", "readOnly": True}],
                        "startupProbe": {"tcpSocket": {"port": 6379},
                                         "periodSeconds": 5, "failureThreshold": 30},
                        "readinessProbe": {"exec": {"command": ["sh", "-c", ready]},
                                           "periodSeconds": 10, "timeoutSeconds": 3},
                        "livenessProbe": {"tcpSocket": {"port": 6379},
                                          "periodSeconds": 15, "failureThreshold": 3},
                    }],
                    "volumes": [{"name": "config",
                                 "configMap": {"name": f"{name}-config"}}],
                },
            },
        },
    }
    if not env:
        sts["spec"]["template"]["spec"]["containers"][0].pop("env")

    if spec.persistence != "none":
        claim: dict[str, Any] = {
            "metadata": {"name": "data"},
            "spec": {"accessModes": ["ReadWriteOnce"],
                     "resources": {"requests": {"storage": spec.storage_size}}},
        }
        if spec.storage_class:
            claim["spec"]["storageClassName"] = spec.storage_class
        sts["spec"]["volumeClaimTemplates"] = [claim]
    else:
        sts["spec"]["template"]["spec"]["volumes"].append(
            {"name": "data", "emptyDir": {}})
    objs.append(sts)

    # one Service for writes (primary only), one for reads (everything)
    objs.append({
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": name, "namespace": ns, "labels": labels,
                     "annotations": {"redis-deployer/role": "primary (writes)"}},
        "spec": {"type": spec.service_type, "selector": {
            "app": name, "statefulset.kubernetes.io/pod-name": f"{name}-0"},
            "ports": [{"name": "redis", "port": 6379, "targetPort": 6379}]},
    })
    objs.append({
        "apiVersion": "v1", "kind": "Service",
        "metadata": {"name": f"{name}-read", "namespace": ns, "labels": labels,
                     "annotations": {"redis-deployer/role": "all pods (reads)"}},
        "spec": {"type": "ClusterIP", "selector": {"app": name},
                 "ports": [{"name": "redis", "port": 6379, "targetPort": 6379}]},
    })

    if spec.allow_namespaces:
        objs.append(network_policy(ns, {"app": name}, 6379, spec.allow_namespaces,
                                   f"allow-clients-to-{name}"))
    return objs
