"""Custom resources for the Opstree redis-operator (redis.redis.opstreelabs.in).

The CR shapes below target v1beta2 / operator v0.15.1. Field names in community
operators do shift between releases, so nothing here is trusted blindly: every
deployment server-side dry-runs the CR first and reports the API server's own
rejection, and `crd_fields()` can read the live schema off the cluster to show
exactly what this version accepts.
"""
from __future__ import annotations

import base64
import json
from typing import Any

from . import ocp
from .catalog import OPSTREE_GROUP, OPSTREE_VERSIONS, opstree_topology
from .models import OpstreeSpec

API_VERSION = f"{OPSTREE_GROUP}/v1beta2"


def image_for(spec: OpstreeSpec) -> str:
    if spec.custom_image:
        return spec.custom_image
    for v in OPSTREE_VERSIONS:
        if v["id"] == spec.version_id:
            return v["image"]
    return OPSTREE_VERSIONS[0]["image"]


def _kubernetes_config(spec: OpstreeSpec) -> dict[str, Any]:
    cfg: dict[str, Any] = {
        "image": image_for(spec),
        "imagePullPolicy": "IfNotPresent",
        "resources": {
            "requests": {"cpu": spec.cpu_request, "memory": spec.memory_request},
            "limits": {"cpu": spec.cpu_limit, "memory": spec.memory_limit},
        },
    }
    if spec.auth_enabled:
        cfg["redisSecret"] = {"name": f"{spec.name}-auth", "key": "password"}
    return cfg


def _storage(spec: OpstreeSpec) -> dict[str, Any] | None:
    if not spec.persistence:
        return None
    claim: dict[str, Any] = {
        "spec": {
            "accessModes": ["ReadWriteOnce"],
            "resources": {"requests": {"storage": spec.storage_size}},
        }
    }
    if spec.storage_class:
        claim["spec"]["storageClassName"] = spec.storage_class
    return {"volumeClaimTemplate": claim}


def additional_config(spec: OpstreeSpec) -> str:
    """Extra redis.conf directives the operator layers onto its own defaults.

    maxmemory is the CACHE CAPACITY -- RAM. Without it Redis is unlimited and
    grows until the container hits its memory limit and the kernel OOMKills it,
    which is a crash rather than an eviction.
    """
    lines = ["# generated by redis-deployer"]
    if spec.maxmemory:
        lines.append(f"maxmemory {spec.maxmemory}")
    if spec.maxmemory_policy:
        lines.append(f"maxmemory-policy {spec.maxmemory_policy}")
    if spec.extra_config:
        lines.append("")
        lines.append(spec.extra_config.strip())
    return "\n".join(lines) + "\n"


def manifests(spec: OpstreeSpec, password: str) -> list[dict]:
    topo = opstree_topology(spec.topology) or {}
    ns, name = spec.namespace, spec.name
    labels = {"app": name, "app.kubernetes.io/name": name,
              "app.kubernetes.io/managed-by": "redis-deployer",
              "redis-deployer/topology": spec.topology}

    objs: list[dict] = [
        {"apiVersion": "v1", "kind": "Namespace",
         "metadata": {"name": ns, "labels": {"name": ns}}},
    ]
    if spec.auth_enabled:
        objs.append({
            "apiVersion": "v1", "kind": "Secret",
            "metadata": {"name": f"{name}-auth", "namespace": ns, "labels": labels},
            "type": "Opaque",
            "data": {"password": base64.b64encode(password.encode()).decode()},
        })

    body: dict[str, Any] = {"kubernetesConfig": _kubernetes_config(spec)}
    store = _storage(spec)

    cfg_name = f"{name}-redis-config"
    if spec.maxmemory or spec.maxmemory_policy or spec.extra_config:
        objs.append({
            "apiVersion": "v1", "kind": "ConfigMap",
            "metadata": {"name": cfg_name, "namespace": ns, "labels": labels},
            # the operator reads this key and appends it to its own redis.conf
            "data": {"redis-additional.conf": additional_config(spec)},
        })
        redis_config = {"additionalRedisConfig": cfg_name}
    else:
        redis_config = None

    if spec.topology == "standalone":
        if store:
            body["storage"] = store
        if redis_config:
            body["redisConfig"] = redis_config

    elif spec.topology == "replication":
        body["clusterSize"] = max(2, spec.size)
        if store:
            body["storage"] = store
        if redis_config:
            body["redisConfig"] = redis_config

    elif spec.topology == "sentinel":
        # Sentinel does not hold data: it watches an existing RedisReplication
        body["clusterSize"] = max(3, spec.size)
        body["redisSentinelConfig"] = {
            "redisReplicationName": spec.replication_name or f"{name}-replication",
            "masterGroupName": spec.master_group,
            "quorum": str(spec.quorum),
        }

    elif spec.topology == "cluster":
        body["clusterSize"] = max(3, spec.size)
        body["clusterVersion"] = "v7"
        body["persistenceEnabled"] = bool(spec.persistence)
        # a cluster configures leaders and followers separately
        body["redisLeader"] = {"redisConfig": redis_config} if redis_config else {}
        body["redisFollower"] = {"redisConfig": redis_config} if redis_config else {}
        if store:
            body["storage"] = store

    objs.append({
        "apiVersion": API_VERSION,
        "kind": topo.get("kind", "Redis"),
        "metadata": {"name": name, "namespace": ns, "labels": labels},
        "spec": body,
    })
    return objs


def crd_fields(kubeconfig: str, kind: str) -> dict[str, Any]:
    """Read the installed CRD's own schema, so the UI can show what this
    operator version actually accepts rather than what the docs claimed."""
    plural = {"Redis": "redis", "RedisReplication": "redisreplications",
              "RedisSentinel": "redissentinels", "RedisCluster": "redisclusters"}
    crd = f"{plural.get(kind, kind.lower())}.{OPSTREE_GROUP}"
    p = ocp.run(kubeconfig, ["get", "crd", crd, "-o", "json"], check=False, timeout=60)
    if p.returncode != 0:
        return {"present": False, "crd": crd}
    try:
        d = json.loads(p.stdout)
    except Exception:
        return {"present": False, "crd": crd}

    versions = d["spec"].get("versions", [])
    served = [v for v in versions if v.get("served")]
    storage = next((v for v in served if v.get("storage")), served[0] if served else {})
    props = (((storage.get("schema") or {}).get("openAPIV3Schema") or {})
             .get("properties", {}).get("spec", {}).get("properties", {}))
    return {
        "present": True, "crd": crd,
        "version": storage.get("name"),
        "served_versions": [v["name"] for v in served],
        "spec_fields": sorted(props.keys()),
    }
